#pragma once

#include <juce_core/juce_core.h>
#include <random>
#include <cmath>

/**
 * NoiseGenerator - Analog-Style Noise Generator
 *
 * Implements subtle noise generation to add texture and realism to the Reese bass.
 *
 * Analog circuits have inherent noise from:
 * - Transistor thermal noise (white noise)
 * - Op-amp noise (pink noise)
 * - Power supply ripple
 *
 * Adding subtle noise (at -60dB to -40dB level) creates:
 * - Organic, "alive" sound
 * - Covers up digital quantization artifacts
 * - Adds high-frequency content that makes sound "open"
 *
 * Noise types:
 * - White noise: Flat spectrum (all frequencies equal power)
 * - Pink noise: 1/f spectrum (3dB/octave rolloff, more "natural")
 */
class NoiseGenerator
{
public:
    enum class NoiseColor
    {
        WHITE,  // Flat spectrum
        PINK    // 1/f spectrum (more natural)
    };

    NoiseGenerator();

    /**
     * Prepare the module for processing
     * @param sampleRate The sample rate in Hz
     */
    void prepare(double sampleRate);

    /**
     * Generate a single noise sample
     * @return Noise sample
     */
    float generateSample();

    /**
     * Apply noise to a signal
     * @param cleanSignal The input signal
     * @return Signal + noise
     */
    float apply(float cleanSignal);

    /**
     * Set the noise amount
     * @param amount 0.0-1.0 (maps to -60dB to -40dB internally)
     */
    void setAmount(float amount);

    /**
     * Set the noise color
     * @param color White or Pink
     */
    void setColor(NoiseColor color);

    /**
     * Reset internal state
     */
    void reset();

private:
    // Sample rate
    double sampleRate = 44100.0;

    // Random number generator for white noise
    std::mt19937 rng;
    std::uniform_real_distribution<float> distribution;

    // Parameters
    float noiseAmount = 0.2f;  // 0.0-1.0 (user control)
    NoiseColor currentColor = NoiseColor::PINK;

    // Pink noise filter state (using Paul Kellet's implementation)
    // Pink noise is generated by filtering white noise
    float b0 = 0.0f;
    float b1 = 0.0f;
    float b2 = 0.0f;
    float b3 = 0.0f;
    float b4 = 0.0f;
    float b5 = 0.0f;
    float b6 = 0.0f;

    // Generate white noise
    float generateWhiteNoise();

    // Generate pink noise (1/f spectrum)
    float generatePinkNoise();

    // Convert noise amount (0.0-1.0) to dB gain (-60dB to -40dB)
    float amountToGain(float amount);
};
